### ISSUE TITLE
Thumbnail/Gallery view crashes

### ISSUE THREAD

**Issue by utterbull** [utterbull/happypanda#3]
The thumbnail/Gallery view causes HappyPanda to crash.

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtWidgets      	0x000000010f93ca24 QFileIconEngine::pixmap(QSize const&, QIcon::Mode, QIcon::State) + 356
1   org.qt-project.QtGui          	0x000000010fd99329 QPixmapIconEngine::paint(QPainter*, QRect const&, QIcon::Mode, QIcon::State) + 297
2   org.qt-project.QtGui          	0x000000010fd9c61f QIcon::paint(QPainter*, QRect const&, QFlags<Qt::AlignmentFlag>, QIcon::Mode, QIcon::State) const + 351
3   QtGui.so                      	0x0000000110c50b05 meth_QIcon_paint(_object*, _object*, _object*) + 325
4   org.python.python             	0x000000010eab8895 PyEval_EvalFrameEx + 18109
5   org.python.python             	0x000000010eab4029 PyEval_EvalCodeEx + 1593
6   org.python.python             	0x000000010ea42fb5 function_call + 372
7   org.python.python             	0x000000010ea22a5b PyObject_Call + 103
8   org.python.python             	0x000000010ea3435d method_call + 140
9   org.python.python             	0x000000010ea22a5b PyObject_Call + 103
10  org.python.python             	0x000000010eabb167 PyEval_CallObjectWithKeywords + 93
11  sip.so                        	0x000000011092e15e sip_api_call_method + 206
12  QtWidgets.so                  	0x000000010f0ea48c sipVH_QtWidgets_26(PyGILState_STATE, void (*)(_sipSimpleWrapper*, PyGILState_STATE), _sipSimpleWrapper*, _object*, QPainter*, QStyleOptionViewItem const&, QModelIndex const&) + 204
13  QtWidgets.so                  	0x000000010f2953d5 sipQStyledItemDelegate::paint(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) const + 117
14  org.qt-project.QtWidgets      	0x000000010f8d505a QListView::paintEvent(QPaintEvent*) + 2218
15  QtWidgets.so                  	0x000000010f21acf1 sipQListView::paintEvent(QPaintEvent*) + 129
16  org.qt-project.QtWidgets      	0x000000010f697cfa QWidget::event(QEvent*) + 2170
17  org.qt-project.QtWidgets      	0x000000010f78b12d QFrame::event(QEvent*) + 45
18  org.qt-project.QtWidgets      	0x000000010f81121a QAbstractScrollArea::viewportEvent(QEvent*) + 170
19  org.qt-project.QtWidgets      	0x000000010f8b3abd QAbstractItemView::viewportEvent(QEvent*) + 1453
20  QtWidgets.so                  	0x000000010f219e14 sipQListView::viewportEvent(QEvent*) + 116
21  org.qt-project.QtWidgets      	0x000000010f811d45 QAbstractScrollAreaFilter::eventFilter(QObject*, QEvent*) + 37
22  org.qt-project.QtCore         	0x00000001104d36d9 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 201
23  org.qt-project.QtWidgets      	0x000000010f658463 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 291
24  org.qt-project.QtWidgets      	0x000000010f65b766 QApplication::notify(QObject*, QEvent*) + 8022
25  QtWidgets.so                  	0x000000010f11a04f sipQApplication::notify(QObject*, QEvent*) + 127
26  org.qt-project.QtCore         	0x00000001104d33c3 QCoreApplication::notifyInternal(QObject*, QEvent*) + 115
27  org.qt-project.QtWidgets      	0x000000010f69161f QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 3119
28  org.qt-project.QtWidgets      	0x000000010f664e30 QWidgetBackingStore::doSync() + 4112
29  org.qt-project.QtWidgets      	0x000000010f697fc6 QWidget::event(QEvent*) + 2886
30  org.qt-project.QtWidgets      	0x000000010f7a1811 QMainWindow::event(QEvent*) + 929
31  QtWidgets.so                  	0x000000010f229704 sipQMainWindow::event(QEvent*) + 116
32  org.qt-project.QtWidgets      	0x000000010f658473 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 307
33  org.qt-project.QtWidgets      	0x000000010f65b766 QApplication::notify(QObject*, QEvent*) + 8022
34  QtWidgets.so                  	0x000000010f11a04f sipQApplication::notify(QObject*, QEvent*) + 127
35  org.qt-project.QtCore         	0x00000001104d408c QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 956
36  libqcocoa.dylib               	0x00000001141bc76e QCocoaEventDispatcherPrivate::processPostedEvents() + 190
37  libqcocoa.dylib               	0x00000001141bcfe1 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 33
38  com.apple.CoreFoundation      	0x00007fff8e0a9a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
39  com.apple.CoreFoundation      	0x00007fff8e09bb8d __CFRunLoopDoSources0 + 269
40  com.apple.CoreFoundation      	0x00007fff8e09b1bf __CFRunLoopRun + 927
41  com.apple.CoreFoundation      	0x00007fff8e09abd8 CFRunLoopRunSpecific + 296
42  com.apple.HIToolbox           	0x00007fff83cca56f RunCurrentEventLoopInMode + 235
43  com.apple.HIToolbox           	0x00007fff83cca1ee ReceiveNextEventCommon + 179
44  com.apple.HIToolbox           	0x00007fff83cca12b _BlockUntilNextEventMatchingListInModeWithFilter + 71
45  com.apple.AppKit              	0x00007fff8e9078ab _DPSNextEvent + 978
46  com.apple.AppKit              	0x00007fff8e906e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
47  com.apple.AppKit              	0x00007fff8ead2887 -[NSApplication _realDoModalLoop:peek:] + 666
48  com.apple.AppKit              	0x00007fff8eacee76 -[NSApplication runModalForWindow:] + 119
49  com.apple.AppKit              	0x00007fff8eb80953 -[NSAlert runModal] + 144
50  com.apple.AppKit              	0x00007fff8ebb81bd __55-[NSPersistentUIRestorer promptToIgnorePersistentState]_block_invoke + 1037
51  com.apple.AppKit              	0x00007fff8ebb7d6e -[NSApplication _suppressFinishLaunchingFromEventHandlersWhilePerformingBlock:] + 28
52  com.apple.AppKit              	0x00007fff8ebb7d0d -[NSPersistentUIRestorer promptToIgnorePersistentState] + 247
53  com.apple.AppKit              	0x00007fff8e90eb6a -[NSApplication _reopenWindowsAsNecessaryIncludingRestorableState:registeringAsReady:completionHandler:] + 255
54  com.apple.AppKit              	0x00007fff8e90e939 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 561
55  com.apple.AppKit              	0x00007fff8e90e385 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 244
56  com.apple.Foundation          	0x00007fff8352a748 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 290
57  com.apple.Foundation          	0x00007fff8352a5b9 _NSAppleEventManagerGenericHandler + 102
58  com.apple.AE                  	0x00007fff8b94734c aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 531
59  com.apple.AE                  	0x00007fff8b9470c9 dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 31
60  com.apple.AE                  	0x00007fff8b946fd3 aeProcessAppleEvent + 295
61  com.apple.HIToolbox           	0x00007fff83cd8c6e AEProcessAppleEvent + 56
62  com.apple.AppKit              	0x00007fff8e907da2 _DPSNextEvent + 2249
63  com.apple.AppKit              	0x00007fff8e906e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
64  com.apple.AppKit              	0x00007fff8e8fcaf3 -[NSApplication run] + 594
65  libqcocoa.dylib               	0x00000001141bbf3a QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2266
66  org.qt-project.QtCore         	0x00000001104d0b2c QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 412
67  org.qt-project.QtCore         	0x00000001104d396a QCoreApplication::exec() + 346
68  QtWidgets.so                  	0x000000010f11ac50 meth_QApplication_exec_(_object*, _object*) + 80
69  org.python.python             	0x000000010eab8895 PyEval_EvalFrameEx + 18109
70  org.python.python             	0x000000010eab4029 PyEval_EvalCodeEx + 1593
71  org.python.python             	0x000000010eabbadb fast_function + 321
72  org.python.python             	0x000000010eab86fa PyEval_EvalFrameEx + 17698
73  org.python.python             	0x000000010eab4029 PyEval_EvalCodeEx + 1593
74  org.python.python             	0x000000010eabbadb fast_function + 321
75  org.python.python             	0x000000010eab86fa PyEval_EvalFrameEx + 17698
76  org.python.python             	0x000000010eab4029 PyEval_EvalCodeEx + 1593
77  org.python.python             	0x000000010eab39ea PyEval_EvalCode + 63
78  org.python.python             	0x000000010ead697d run_mod + 58
79  org.python.python             	0x000000010ead6c1c PyRun_FileExFlags + 178
80  org.python.python             	0x000000010ead6426 PyRun_SimpleFileExFlags + 865
81  org.python.python             	0x000000010eae9622 Py_Main + 3130
82  org.python.python             	0x000000010ea11e27 0x10ea10000 + 7719
83  libdyld.dylib                 	0x00007fff911a45c9 start + 1
```

**Comment by utterbull** [comment]
**Temporary Fix**
Switch to list view prior to importing galleries. Do NOT switch back to thumbnail view.

**Comment by utterbull** [comment]
-d Log
```
07-08 12:56 INFO   __main__ Happypanda Version 0.2
07-08 12:56 INFO   __main__ OS: Darwin 14.4.0

07-08 12:56 DEBUG  __main__ Init DB Conn: OK
07-08 12:56 INFO   __main__ DB Version: 0.21
07-08 12:56 DEBUG  database.db Start Database Thread: OK
07-08 12:56 DEBUG  database.db Checking DB Version
07-08 12:56 DEBUG  app    Create manga display: OK
07-08 12:56 DEBUG  app    Create toolbar: OK
07-08 12:56 DEBUG  app    Create statusbar: OK
07-08 12:56 DEBUG  app    Create system tray: OK
07-08 12:56 DEBUG  app    Show window: OK
07-08 12:56 DEBUG  app    Create notificationbar: OK
07-08 12:56 DEBUG  app    Window Create: OK
07-08 12:56 INFO   app    Invoking first time level 3
07-08 12:56 INFO   __main__ Select defaultstyle: OK
07-08 12:56 DEBUG  database.db b'SELECT * FROM series'
07-08 12:56 DEBUG  database.db b'SELECT * FROM series'
07-08 12:56 DEBUG  __main__ Create temp: OK
07-08 12:56 DEBUG  database.db b'SELECT * FROM series'
07-08 12:56 DEBUG  database.db b'SELECT * FROM series'
07-08 12:56 DEBUG  app    Checking Update
07-08 12:56 INFO   requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): raw.githubusercontent.com
07-08 12:56 ERROR  app    Checking Update: FAIL
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 267, in ssl_wrap_socket
    context.load_verify_locations(ca_certs)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 269, in ssl_wrap_socket
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/utterbull/Desktop/happypanda_working/version/app.py", line 297, in fetch_vs
    verify='cacert.pem')
  File "/usr/local/lib/python3.4/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 2] No such file or directory
07-08 12:56 INFO   app    Received version: this is a very long text which is is sure to be over limit
Current version: 0.2
07-08 12:59 DEBUG  database.db b'SELECT * FROM series'
07-08 12:59 DEBUG  database.db b'SELECT * FROM series'
07-08 12:59 INFO   fetch  Gallery folder is not empty
07-08 12:59 INFO   fetch  Found 2 items
07-08 12:59 INFO   fetch  Treating each subfolder as chapter
07-08 12:59 DEBUG  database.db b'SELECT * FROM series'
07-08 12:59 DEBUG  database.db b'SELECT * FROM series'
07-08 12:59 INFO   fetch  Creating gallery: b'.DS_Store'
07-08 12:59 WARNING fetch  Skipped /Users/utterbull/Desktop/Panda Test Folder/.DS_Store in local search
07-08 12:59 INFO   fetch  Treating each subfolder as chapter
07-08 12:59 DEBUG  database.db b'SELECT * FROM series'
07-08 12:59 DEBUG  database.db b'SELECT * FROM series'
07-08 12:59 INFO   fetch  Creating gallery: b'Cool Shades Krillin'
07-08 12:59 INFO   fetch  Gallery source is a directory
07-08 12:59 INFO   fetch  Gallery successful created: b'Cool Shades Krillin'
07-08 12:59 INFO   fetch  Local search: OK
07-08 12:59 INFO   fetch  Created 1 items
07-08 12:59 INFO   app    Populating DB from gallery folder: OK
07-08 12:59 INFO   app    Populating DB from gallery folder
07-08 12:59 INFO   gallerydb Added method to queue
07-08 12:59 DEBUG  gallerydb Method name: add_gallery_return
07-08 12:59 INFO   gallerydb Processing a method from queue...
07-08 12:59 INFO   gallerydb Recevied gallery: b'/Users/utterbull/Desktop/Panda Test Folder/Cool Shades Krillin'
07-08 12:59 INFO   utils  Getting image from folder
07-08 12:59 DEBUG  database.db b'INSERT INTO series(title, artist, profile, series_path, is_archive,\n\t\t\t\t\tinfo, type, fav, status, pub_date, date_added, last_read, link, last_update,\n\t\t\t\t\ttimes_read, exed)\n\t\t\t\tVALUES(:title, :artist, :profile, :series_path, :is_archive, :info, :type, :fav,\n\t\t\t\t\t:status, :pub_date, :date_added, :last_read, :link, :last_update,\n\t\t\t\t\t:times_read, :exed)'
07-08 12:59 DEBUG  database.db b"{'info': 'No description..', 'times_read': 0, 'type': 'None', 'link': b'', 'db_v': 0.21, 'status': 'None', 'series_path': b'/Users/utterbull/Desktop/Panda Test Folder/Cool Shades Krillin', 'profile': b'/Users/utterbull/Desktop/happypanda_working/version/db/thumbnails/b8e4ca2d-c2eb-4917-852b-d0c4fb6b3ae8.png', 'is_archive': 0, 'date_added': datetime.datetime(2015, 8, 7, 12, 59, 23), 'artist': '', 'last_update': 'None', 'language': 'Other', 'fav': 0, 'last_read': 'None', 'title': 'Cool Shades Krillin', 'exed': 0, 'pub_date': 'None', 'path_in_archive': b''}"
07-08 12:59 DEBUG  database.db b'\n\t\t\tINSERT INTO chapters(series_id, chapter_number, chapter_path, in_archive)\n\t\t\tVALUES(:series_id, :chapter_number, :chapter_path, :in_archive)'
07-08 12:59 DEBUG  database.db b"{'chapter_path': b'/Users/utterbull/Desktop/Panda Test Folder/Cool Shades Krillin', 'chapter_number': 0, 'series_id': 1, 'in_archive': 0}"
07-08 12:59 DEBUG  database.db b'SELECT * FROM series WHERE series_id=?'
07-08 12:59 DEBUG  database.db b'(1,)'
07-08 12:59 DEBUG  database.db b'SELECT chapter_number, chapter_path\n\t\t\t\t\t\t\tFROM chapters WHERE series_id=?'
07-08 12:59 DEBUG  database.db b'(1,)'
07-08 12:59 DEBUG  database.db b'SELECT tags_mappings_id FROM series_tags_map WHERE series_id=?'
07-08 12:59 DEBUG  database.db b'(1,)'
07-08 12:59 DEBUG  database.db b'SELECT hash FROM hashes WHERE series_id=?'
07-08 12:59 DEBUG  database.db b'(1,)'
07-08 12:59 INFO   gallerydb Added method to queue
07-08 12:59 DEBUG  gallerydb Method name: open_chapter
07-08 12:59 INFO   gallerydb Added method to queue
07-08 12:59 DEBUG  gallerydb Method name: modify_gallery
07-08 12:59 INFO   gallerydb Processing a method from queue...
07-08 12:59 INFO   gallerydb Processing a method from queue...
07-08 12:59 DEBUG  database.db b'UPDATE series SET times_read=? WHERE series_id=?'
07-08 12:59 DEBUG  database.db b'(1, 1)'
```
Terminal Output
```
2015-08-07 12:59:16.415 Python[53165:1612503] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd7ea0 h=--& v=-&- V:[_NSBrowserColumnsContainerView:0x7fb7c2eeb190]-(0)-|   (Names: '|':NSClipView:0x7fb7c2e50030 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd62c0 h=--& v=-&- V:|-(0)-[FI_TBrowserColumnView:0x7fb7c2c988e0]   (Names: '|':_NSBrowserColumnsContainerView:0x7fb7c2eeb190 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd7ef0 h=--& v=-&- V:|-(0)-[_NSBrowserColumnsContainerView:0x7fb7c2eeb190]   (Names: '|':NSClipView:0x7fb7c2e50030 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd6270 h=--& v=-&- V:[FI_TBrowserColumnView:0x7fb7c2c988e0]-(0)-|   (Names: '|':_NSBrowserColumnsContainerView:0x7fb7c2eeb190 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd8380 h=-&- v=-&- V:|-(0)-[NSClipView:0x7fb7c2e50030]   (Names: '|':_NSBrowserScrollView:0x7fb7c2db5b20 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd83d0 h=-&- v=-&- V:[NSClipView:0x7fb7c2e50030]-(15)-|   (Names: '|':_NSBrowserScrollView:0x7fb7c2db5b20 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd8ab0 h=--& v=--& V:[_NSBrowserScrollView:0x7fb7c2db5b20(0)]>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd62c0 h=--& v=-&- V:|-(0)-[FI_TBrowserColumnView:0x7fb7c2c988e0]   (Names: '|':_NSBrowserColumnsContainerView:0x7fb7c2eeb190 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
2015-08-07 12:59:16.416 Python[53165:1612503] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd7ea0 h=--& v=-&- V:[_NSBrowserColumnsContainerView:0x7fb7c2eeb190]-(0)-|   (Names: '|':NSClipView:0x7fb7c2e50030 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd7ef0 h=--& v=-&- V:|-(0)-[_NSBrowserColumnsContainerView:0x7fb7c2eeb190]   (Names: '|':NSClipView:0x7fb7c2e50030 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd8380 h=-&- v=-&- V:|-(0)-[NSClipView:0x7fb7c2e50030]   (Names: '|':_NSBrowserScrollView:0x7fb7c2db5b20 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd83d0 h=-&- v=-&- V:[NSClipView:0x7fb7c2e50030]-(15)-|   (Names: '|':_NSBrowserScrollView:0x7fb7c2db5b20 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd8ab0 h=--& v=--& V:[_NSBrowserScrollView:0x7fb7c2db5b20(0)]>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd7ef0 h=--& v=-&- V:|-(0)-[_NSBrowserColumnsContainerView:0x7fb7c2eeb190]   (Names: '|':NSClipView:0x7fb7c2e50030 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
2015-08-07 12:59:16.417 Python[53165:1612503] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd8380 h=-&- v=-&- V:|-(0)-[NSClipView:0x7fb7c2e50030]   (Names: '|':_NSBrowserScrollView:0x7fb7c2db5b20 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd83d0 h=-&- v=-&- V:[NSClipView:0x7fb7c2e50030]-(15)-|   (Names: '|':_NSBrowserScrollView:0x7fb7c2db5b20 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd8ab0 h=--& v=--& V:[_NSBrowserScrollView:0x7fb7c2db5b20(0)]>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x7fb7c2bd83d0 h=-&- v=-&- V:[NSClipView:0x7fb7c2e50030]-(15)-|   (Names: '|':_NSBrowserScrollView:0x7fb7c2db5b20 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
Segmentation fault: 11
```

**Comment by utterbull** [comment]
Fixed in Pewpews Alpha branch as of the time of this post.
